import { NextResponse } from 'next/server'

export async function GET() {
  const allProducts = [
    {
      content: [
        {
          id: 501,
          name: '수트케이스 슈트케이스 양복가방 가먼트백수트케이스 슈트케이스 양복가방 가먼트백수트케이스 슈트케이스 양복가방 가먼트백수트케이스 슈트케이스 양복가방 가먼트백',
          labels: 'NONE',
          originPrice: 4500,
          discountPrice: 3200,
          isDiscount: true,
          brand: '더웨이나인',
          mainImage: 'https://shopping-phinf.pstatic.net/main_8207483/82074834562.1.jpg',
        },
        {
          id: 518,
          name: '슈트케이스 정장케이스 양복케이스 수트 부직포 커버',
          labels: 'PROMOTION',
          originPrice: 3500,
          discountPrice: 3500,
          isDiscount: true,
          brand: '다린 지갑케이스',
          mainImage: 'https://shopping-phinf.pstatic.net/main_8118973/81189738146.jpg',
        },
        {
          id: 529,
          name: '슈트케이스 정장케이스 양복케이스 수트 부직포 커버',
          labels: 'SPECIAL_PRICE',
          originPrice: 4000,
          discountPrice: 3500,
          isDiscount: true,
          brand: '미마 지갑케이스',
          mainImage: 'https://shopping-phinf.pstatic.net/main_8118983/81189837302.jpg',
        },
        {
          id: 539,
          name: '여행용 슈트케이스 양복가방 수트백',
          labels: 'SPECIAL_PRICE',
          originPrice: 6580,
          discountPrice: 6380,
          isDiscount: true,
          brand: '내아스토어',
          mainImage: 'https://shopping-phinf.pstatic.net/main_8639391/86393919483.jpg',
        },
        {
          id: 521,
          name: '아라홍스 슈트케이스 양복가방 가먼트백 여행 출장 방수원단 정장보관',
          labels: 'PROMOTION',
          originPrice: 15900,
          discountPrice: 9900,
          isDiscount: false,
          brand: '아라홍스',
          mainImage: 'https://shopping-phinf.pstatic.net/main_8805283/88052833575.jpg',
        },
        {
          id: 503,
          name: '진브릭 슈트케이스 가먼트백 양복가방',
          labels: 'SPECIAL_PRICE',
          originPrice: 24500,
          discountPrice: 15500,
          isDiscount: false,
          brand: '데이텀에프',
          mainImage: 'https://shopping-phinf.pstatic.net/main_8630491/86304910135.2.jpg',
        },
        {
          id: 530,
          name: '접이식 보스턴백 정장 양복 가방 슈트케이스 의류보관 가먼트백 출장용 여행용 멀티포켓',
          labels: 'SPECIAL_PRICE',
          originPrice: 24300,
          discountPrice: 23800,
          isDiscount: false,
          brand: '써커스라이프2',
          mainImage: 'https://shopping-phinf.pstatic.net/main_8885553/88855530085.jpg',
        },
        {
          id: 504,
          name: '여행용 보스턴백 4in1 수트케이스 슈트케이스 양복가방 백팩 출장 가먼트백 정장 캐리어',
          labels: 'SPECIAL_PRICE',
          originPrice: 59000,
          discountPrice: 28000,
          isDiscount: false,
          brand: '록스프링',
          mainImage: 'https://shopping-phinf.pstatic.net/main_8854221/88542212729.jpg',
        },
        {
          id: 525,
          name: '여행 접이식 보스턴백 정장 양복 가방 슈트케이스 의류보관 가먼트백 출장용 멀티포켓',
          labels: 'SPECIAL_PRICE',
          originPrice: 29900,
          discountPrice: 29900,
          isDiscount: false,
          brand: '아이데이션',
          mainImage: 'https://shopping-phinf.pstatic.net/main_8829255/88292555874.jpg',
        },
        {
          id: 540,
          name: 'XONIX 합창단원복 슈트케이스 정장가먼트백 양복옷걸이 단체옷가방 드레스',
          labels: 'NONE',
          originPrice: 36000,
          discountPrice: 32400,
          isDiscount: false,
          brand: '조닉스 아모래가방',
          mainImage: 'https://shopping-phinf.pstatic.net/main_8744767/87447672325.8.jpg',
        },
        {
          id: 545,
          name: '수트 케이스 양복 가방 출장 방지 정장 구김 슈트 코트 여행용 양복가방',
          labels: 'SPECIAL_PRICE',
          originPrice: 54860,
          discountPrice: 38400,
          isDiscount: false,
          brand: '진이네1029',
          mainImage: 'https://shopping-phinf.pstatic.net/main_8762656/87626564961.jpg',
        },
        {
          id: 508,
          name: '수트케이스 여행 출장 가방 가먼트백 수트 정장 양복 슈트 케이스',
          labels: 'PROMOTION',
          originPrice: 99000,
          discountPrice: 39000,
          isDiscount: false,
          brand: 'CUBE-BOX',
          mainImage: 'https://shopping-phinf.pstatic.net/main_8173364/81733644772.11.jpg',
        },
      ],
      page: {
        size: 12,
        number: 0,
        totalElements: 17,
        totalPages: 2,
      },
    },
  ]

  return NextResponse.json(allProducts)
}
