export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  FIND: {
    ID: '/find-id',
    PW: '/find-pw',
  },
  MYPAGE: '/mypage',
  EDIT_PROFILE: '/edit-profile',
  CUSTOM: '/custom',
  ORDERS: '/orders',
  RECENT: '/recent-views',
  FAVORITES: '/favorites',
  REVIEWS: '/reviews',
  RESTOCK: '/restock-alerts',
  NOTICE: '/notice',
  INQUIRY: '/inquiry',
  FAQ: '/faq',
  RECOMMEND: '/recommend',
  SALE: '/sale',
  BEST: '/best',
  CATEGORIES: {
    CLOTHES: '/categories/clothes',
    ACCESSORIES: '/categories/accessories',
    DIGITAL: '/categories/digital',
    FURNITURE: '/categories/furniture',
    FOOD: '/categories/food',
  },
} as const
