export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  FIND: {
    ID: '/find-id',
    PW: '/find-pw',
  },
  MYPAGE: '/mypage',
  EDIT_PROFILE: '/edit-profile',
  CUSTOM: '/custom',
  PURCHASE: '/purchase',
  PURCHASE_COMPLETE: '/purchase-complete',
  ORDERS: '/orders',
  RECENT: '/recent-views',
  WISHLIST: '/wishlist',
  REVIEWS: '/reviews',
  REVIEW_REGISTER: '/reviews/register',
  REVIEW_COMPLETE: '/reviews/complete',
  RESTOCK: '/restock-alerts',
  NOTICE: '/notice',
  INQUIRY: '/inquiry',
  FAQ: '/faq',
  RECOMMEND: '/recommend',
  SALE: '/sale',
  BEST: '/best',
  CART: '/cart',
  CATEGORIES: '/categories',
  PRODUCT: '/product',
  SEARCH: '/search',
} as const
