name: 'Bug 등록'
description: 'fix 관련 이슈를 생성'
labels: [fix]
title: '[fix] 버그 제목'
body:
  - type: textarea
    id: description
    attributes:
      label: '버그 내용(Description)'
      description: '버그에 대해서 설명해주세요'
    validations:
      required: true

  - type: textarea
    id: situation
    attributes:
      label: '재현 상황(Situation)'
      description: '버그 발생 상황에 대해서 단계별로 설명해주세요'
      value: |
        1. Step1
        2. Step2
    validations:
      required: true
