import React from 'react'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import ViewportAdjuster from '@/components/common/ViewportAdjuster'
import '@/styles/globals.css'

export const metadata: Metadata = {
  title: '지혜 | Ji-hye',
  description: 'Generated by create next app',
}

export const pretendard = localFont({
  src: '../../node_modules/pretendard/dist/web/variable/woff2/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendard.className} antialiased`}>
        <ViewportAdjuster />
        {children}
      </body>
    </html>
  )
}
