import React from 'react'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import ViewportAdjuster from '@/components/common/ViewportAdjuster'
import Header from '@/components/layout/Header/Header'
import Footer from '@/components/layout/Footer/Footer'
import Providers from '@/providers/Providers'
import '@/styles/globals.css'
import { Toaster } from '@/components/common/Toast/Toast'

export const metadata: Metadata = {
  title: '지혜 | Ji-hye',
  description: 'Generated by create next app',
}

export const pretendard = localFont({
  src: '../../node_modules/pretendard/dist/web/variable/woff2/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendard.className} antialiased text-strong`}>
        <Toaster />
        <ViewportAdjuster />
        <Providers>
          <div className="relative flex flex-col min-h-screen">
            <Header />
            {children}
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  )
}
