import React from 'react'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import ViewportAdjuster from '@/components/common/ViewportAdjuster'
import '@/styles/globals.css'
import Header from '@/components/layout/Header/Header'
import Footer from '@/components/layout/Footer'
import { initMSW } from '@/mocks'
import MSWInitializer from '@/components/common/msw/MSWInitializer'

export const metadata: Metadata = {
  title: '지혜 | Ji-hye',
  description: 'Generated by create next app',
}

export const pretendard = localFont({
  src: '../../node_modules/pretendard/dist/web/variable/woff2/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  initMSW()

  return (
    <html lang="ko">
      <body className={`${pretendard.className} antialiased`}>
        <MSWInitializer />
        <ViewportAdjuster />
        <div className="relative flex flex-col min-h-screen">
          <Header />
          <main className="container flex-1 py-8">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  )
}
